### ISSUE TITLE
fatal error: pcl/surface/on_nurbs/fitting_surface_tdm.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by HuangCongQing** [HuangCongQing/pcl-learning#10]
![image](https://user-images.githubusercontent.com/20675770/96821795-3f35c500-145b-11eb-91c4-fbb24af06269.png)

**Comment by HuangCongQing** [comment]
```c++
 sudo cp -r ./on_nurbs /usr/local/include/pcl-1.9/pcl/surface/
```

将/home/hcq/pcl/pcl/surface/include/pcl/surface/on_nurbs  移动到
**/usr/local/include/pcl-1.9/pcl/surface/**

![image](https://user-images.githubusercontent.com/20675770/96822814-891faa80-145d-11eb-96a6-ef9edf2450fa.png)

**Comment by sun421-cloud** [comment]
您好，请问一下，此目录/home/hcq/pcl/pcl/surface/include/pcl/surface/on_nurbs下面的文件是怎么获得的呢？能简单说说吗？
