### ISSUE TITLE
请问如何实现PCL点云的多目标跟踪?

### ISSUE THREAD

**Issue by WestbrookZero** [HuangCongQing/pcl-learning#13]

**Comment by HuangCongQing** [comment]
有一篇硕士论文代码就是多目标检测与跟踪，我最近也在看，后面把详细注释好的代码放在github上

**Comment by WestbrookZero** [comment]
这个是基于ROS系统下的激光雷达的点云多目标跟踪，我是基于Win10的深度相机的点云多目标跟踪，请问是否以及如何移植？

**Comment by HuangCongQing** [comment]
> 这个是基于ROS系统下的激光雷达的点云多目标跟踪，我是基于Win10的深度相机的点云多目标跟踪，请问是否以及如何移植？

win10也可以安装ROS（ROS你可以理解成C++库），网上有很多安装教程，你可以参考下这个https://blog.csdn.net/zhangrelay/article/details/52705019

**Comment by WestbrookZero** [comment]
谢谢，我之前在Win10上面安装过ROS的Melodic版本，但是运行Qt一直报错，https://github.com/ms-iot/ROSOnWindows/issues/305#issuecomment-751326011，一直都解决不了，所以就放弃了。
