### ISSUE TITLE
/pcl-learning/11surface表面 /1基于多项式重构的平滑和法线估计/resampling.cpp 保存数据为空

### ISSUE THREAD

**Issue by DormouseLi** [HuangCongQing/pcl-learning#18]
使用"../ism_train_cat.pcd" 文件时，结果保存数据为空；使用官方教程代码"../bun0.pcd"有输出。请问是因为mls的参数没调好吗？有没有遇到相同问题的呢？

**Comment by HuangCongQing** [comment]
这个可能"../ism_train_cat.pcd"这个pcd文件经过计算处理结果就应该是空的，你debug下。"../bun0.pcd"有输出算法应该没有问题。
