### ISSUE TITLE
“11surface表面 ”文件夹命名错误导致无法clone

### ISSUE THREAD

**Issue by lantex** [HuangCongQing/pcl-learning#19]
由于“11surface表面 ”的文件夹命名多了一个空格，导致git clone 时出现错误提示
`
fatal: cannot create directory at '11surface表面 ': 无效的参数
`
在解压缩时，不会出现类似问题。但解压后将目录转移位置时，会出现错误提示
`
新建文件夹“11surface表面 ”时出错。无效的文件名
`
系统：ubuntu 20.04

**Comment by HuangCongQing** [comment]
fixed ,Thanks!
