### ISSUE TITLE
如何获得xxx_far_ranges.pcd文件

### ISSUE THREAD

**Issue by cyn-liu** [HuangCongQing/pcl-learning#20]
1、在keypoint章节和range image章节extract border部分，加载xxx.pcd文件后，都需要再加载一个xxx_far_ranges.pcd文件，xxx_far_ranges.pcd文件如何获得？？？
2、如果我选择使用自动生成点云的方式进行后续操作，我的程序都会报错：

No *.pcd file given => Generating example point cloud.
段错误 (核心已转储)

期待回复，感谢！

**Comment by HuangCongQing** [comment]
xxx_far_ranges.pcd 你自己改下名也可以测试：

**常见的pcd文件都在官方github里面，如下图：**

https://github.com/PointCloudLibrary/pcl/tree/pcl-1.9.1/test

![Uploading image.png…]()

**Comment by HuangCongQing** [comment]
我细看了下代码，这个信息属于代码里的提示信息，不影响结果，代码已经更新了哈。
doc: https://www.yuque.com/huangzhongqing/pcl/hxeyrz#q7ZdS
code： https://github.com/HuangCongQing/pcl-learning/tree/master/06range-images%E6%B7%B1%E5%BA%A6%E5%9B%BE%E5%83%8F/2%E4%BB%8E%E6%B7%B1%E5%BA%A6%E5%9B%BE%E4%B8%AD%E6%8F%90%E5%8F%96%E8%BE%B9%E7%95%8C
