### ISSUE TITLE
pcd file can't opened by CloudCompare

### ISSUE THREAD

**Issue by shanhedian2017** [HuangCongQing/pcl-learning#21]
所附的点云文件，pcd和ply格式的，无法用CloudCompare打开，请问楼主遇到这个问题没

**Comment by HuangCongQing** [comment]
请附上报错截图

**Comment by shanhedian2017** [comment]
![image](https://user-images.githubusercontent.com/30818980/212463302-da018dcd-c875-46a1-8d73-b54caa54c49e.png)

**Comment by HuangCongQing** [comment]
可能原因1：文件路径里有中文，换一个全英文路径打开成功。参考：https://blog.csdn.net/qq_42495740/article/details/127998872?
可能原因2：https://blog.csdn.net/qq_52926136/article/details/124985275

建议：先网上搜下相关问题，看有没有解决方法，没有再提问～
